version: '3'

services:

  site:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: ["jekyll", "serve", "-d", "./docs"]

  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: ["jekyll", "build", "-d", "./docs"]

